// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjeTakip.Data;

#nullable disable

namespace ProjeTakip.Migrations
{
    [DbContext(typeof(ProjeTakipContext))]
    [Migration("20250807113711_AddKullaniciToIlerleme")]
    partial class AddKullaniciToIlerleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjeTakip.Models.Birim", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BirimAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("ProjeTakip.Models.Gantt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Asama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Baslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Bitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gun")
                        .HasColumnType("int");

                    b.Property<int>("ProjeID")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ProjeID");

                    b.ToTable("GanttAsamalari");
                });

            modelBuilder.Entity("ProjeTakip.Models.Ilerleme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GanttID")
                        .HasColumnType("int");

                    b.Property<string>("IlerlemeTanimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IlerlemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("int");

                    b.Property<int>("ProjeID")
                        .HasColumnType("int");

                    b.Property<int>("TamamlanmaYuzdesi")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("GanttID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("ProjeID");

                    b.ToTable("Ilerlemeler");
                });

            modelBuilder.Entity("ProjeTakip.Models.Kullanici", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kimlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("ProjeTakip.Models.Proje", b =>
                {
                    b.Property<int>("ProjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjeID"));

                    b.Property<string>("Amac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baskanlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Ekip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kapsam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Maliyet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mudurluk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjeAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("bas")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("bit")
                        .HasColumnType("datetime2");

                    b.Property<string>("olcut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personel")
                        .HasColumnType("int");

                    b.Property<string>("sponsor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjeID");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("ProjeTakip.Models.Sponsor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BirimAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Sponsorler");
                });

            modelBuilder.Entity("ProjeTakip.Models.Gantt", b =>
                {
                    b.HasOne("ProjeTakip.Models.Proje", "Proje")
                        .WithMany("GanttAsamalari")
                        .HasForeignKey("ProjeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("ProjeTakip.Models.Ilerleme", b =>
                {
                    b.HasOne("ProjeTakip.Models.Gantt", "GanttAsama")
                        .WithMany()
                        .HasForeignKey("GanttID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjeTakip.Models.Kullanici", "EkleyenKullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID");

                    b.HasOne("ProjeTakip.Models.Proje", "Proje")
                        .WithMany()
                        .HasForeignKey("ProjeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkleyenKullanici");

                    b.Navigation("GanttAsama");

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("ProjeTakip.Models.Proje", b =>
                {
                    b.Navigation("GanttAsamalari");
                });
#pragma warning restore 612, 618
        }
    }
}
